# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170227_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='course',
            new_name='course_id',
        ),
    ]
