# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
