# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('courses', '0002_auto_20170302_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_creator',
        ),
        migrations.AddField(
            model_name='course',
            name='user_creator',
            field=models.ManyToManyField(null=True, related_name='users', to='login.User'),
        ),
    ]
