# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('courses', '0006_auto_20170227_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='user_creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
    ]
