# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170302_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_creator',
        ),
    ]
