# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('courses', '0008_remove_course_user_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user_creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
